export const booksData = [
  {
    id: "1",
    title: "One Piece Vol. 100",
    author: "Eiichiro Oda",
    publisher: "Elex Media Komputindo",
    publishYear: 2022,
    price: 45000,
    originalPrice: 50000,
    coverImage: "/grand-line-adventure.png",
    rating: 4.9,
    reviewCount: 215,
    stock: 25,
    isNew: false,
    isBestseller: true,
    categories: ["fiction", "manga"],
    language: "Indonesia",
    pageCount: 200,
    dimensions: "11.5 x 17.5 cm",
    isbn: "9786230031083",
    weight: 200,
    synopsis:
      "Volume ke-100 dari seri manga terlaris One Piece. Petualangan Monkey D. Luffy dan kru Topi Jerami berlanjut di Wano Country. Pertempuran melawan Kaido dan Big Mom mencapai klimaksnya saat Luffy berusaha menjadi Raja Bajak Laut dan menemukan harta karun terbesar, One Piece.",
  },
  {
    id: "2",
    title: "Jujutsu Kaisen Vol. 15",
    author: "Gege Akutami",
    publisher: "Elex Media Komputindo",
    publishYear: 2022,
    price: 40000,
    coverImage: "/cursed-clash.png",
    rating: 4.8,
    reviewCount: 180,
    stock: 30,
    isNew: true,
    isBestseller: true,
    categories: ["fiction", "manga"],
    language: "Indonesia",
    pageCount: 192,
    dimensions: "11.5 x 17.5 cm",
    isbn: "9786230035081",
    weight: 190,
    synopsis:
      "Yuji Itadori bergabung dengan Jujutsu Sorcerers untuk melawan kutukan berbahaya dan menyelamatkan dunia. Di volume 15, pertarungan sengit dalam Culling Game terus berlanjut dengan taruhan yang semakin tinggi. Yuji dan teman-temannya harus menghadapi musuh yang semakin kuat.",
  },
  {
    id: "3",
    title: "Spy x Family Vol. 8",
    author: "Tatsuya Endo",
    publisher: "m&c!",
    publishYear: 2022,
    price: 42000,
    originalPrice: 45000,
    coverImage: "/family-mission.png",
    rating: 4.7,
    reviewCount: 165,
    stock: 20,
    isNew: true,
    isBestseller: true,
    categories: ["fiction", "manga"],
    language: "Indonesia",
    pageCount: 200,
    dimensions: "11.5 x 17.5 cm",
    isbn: "9786230034084",
    weight: 195,
    synopsis:
      "Loid Forger, seorang mata-mata, harus membentuk keluarga palsu untuk menjalankan misinya. Tanpa sepengetahuannya, putri angkatnya Anya adalah seorang telepati dan istrinya Yor adalah seorang pembunuh bayaran. Volume 8 melanjutkan petualangan keluarga tidak biasa ini dalam misi mereka untuk menjaga perdamaian.",
  },
  {
    id: "4",
    title: "Demon Slayer: Kimetsu no Yaiba Vol. 23",
    author: "Koyoharu Gotouge",
    publisher: "Elex Media Komputindo",
    publishYear: 2021,
    price: 40000,
    coverImage: "/demon-slayer-vigilance.png",
    rating: 4.9,
    reviewCount: 230,
    stock: 15,
    isNew: false,
    isBestseller: true,
    categories: ["fiction", "manga"],
    language: "Indonesia",
    pageCount: 192,
    dimensions: "11.5 x 17.5 cm",
    isbn: "9786230030086",
    weight: 190,
    synopsis:
      "Volume final dari seri Demon Slayer yang fenomenal. Tanjiro Kamado dan teman-temannya menghadapi pertarungan terakhir melawan Muzan Kibutsuji, raja iblis. Nasib umat manusia dan keluarga Kamado dipertaruhkan dalam pertempuran epik ini.",
  },
  {
    id: "5",
    title: "Chainsaw Man Vol. 11",
    author: "Tatsuki Fujimoto",
    publisher: "m&c!",
    publishYear: 2022,
    price: 45000,
    originalPrice: 50000,
    coverImage: "/chainsaw-demon-hunter.png",
    rating: 4.8,
    reviewCount: 175,
    stock: 22,
    isNew: true,
    isBestseller: false,
    categories: ["fiction", "manga"],
    language: "Indonesia",
    pageCount: 192,
    dimensions: "11.5 x 17.5 cm",
    isbn: "9786230038082",
    weight: 190,
    synopsis:
      "Denji, seorang pemuda miskin yang menjadi hybrid manusia-iblis gergaji mesin setelah membuat perjanjian dengan iblis gergaji mesin. Volume 11 melanjutkan kisah Denji yang penuh aksi dan kekerasan saat dia bekerja sebagai pemburu iblis untuk Public Safety Devil Hunters.",
  },
  {
    id: "6",
    title: "Sword Art Online: Progressive Vol. 8",
    author: "Reki Kawahara",
    publisher: "m&c!",
    publishYear: 2022,
    price: 85000,
    coverImage: "/virtual-horizon.png",
    rating: 4.6,
    reviewCount: 120,
    stock: 18,
    isNew: true,
    isBestseller: true,
    categories: ["fiction", "light-novel"],
    language: "Indonesia",
    pageCount: 256,
    dimensions: "13 x 19 cm",
    isbn: "9786230037085",
    weight: 250,
    synopsis:
      "Sword Art Online: Progressive adalah seri light novel yang menceritakan kembali petualangan Kirito dan Asuna di game VRMMORPG mematikan Sword Art Online, lantai demi lantai. Volume 8 mengikuti perjuangan mereka di lantai yang lebih tinggi dengan tantangan dan musuh yang semakin berbahaya.",
  },
  {
    id: "7",
    title: "That Time I Got Reincarnated as a Slime Vol. 14",
    author: "Fuse",
    publisher: "Elex Media Komputindo",
    publishYear: 2022,
    price: 90000,
    coverImage: "/azure-jelly-tome.png",
    rating: 4.7,
    reviewCount: 145,
    stock: 20,
    isNew: false,
    isBestseller: true,
    categories: ["fiction", "light-novel"],
    language: "Indonesia",
    pageCount: 320,
    dimensions: "13 x 19 cm",
    isbn: "9786230036088",
    weight: 300,
    synopsis:
      "Setelah terbunuh, Satoru Mikami bereinkarnasi di dunia fantasi sebagai slime dengan kemampuan unik untuk menyerap kekuatan lawan. Kini dikenal sebagai Rimuru Tempest, dia membangun negara monster dan menghadapi ancaman dari berbagai kekuatan. Volume 14 melanjutkan petualangan Rimuru saat dia menghadapi konsekuensi dari menjadi Demon Lord.",
  },
  {
    id: "8",
    title: "My Hero Academia Vol. 32",
    author: "Kohei Horikoshi",
    publisher: "m&c!",
    publishYear: 2022,
    price: 42000,
    originalPrice: 48000,
    coverImage: "/hero-academy-cover.png",
    rating: 4.7,
    reviewCount: 155,
    stock: 25,
    isNew: true,
    isBestseller: false,
    categories: ["fiction", "manga"],
    language: "Indonesia",
    pageCount: 192,
    dimensions: "11.5 x 17.5 cm",
    isbn: "9786230039089",
    weight: 190,
    synopsis:
      "Di dunia di mana sebagian besar populasi memiliki kekuatan super atau 'Quirk', Izuku Midoriya bermimpi menjadi pahlawan meskipun dia terlahir tanpa Quirk. Volume 32 melanjutkan pertarungan final antara para pahlawan dan Liga Villain yang dipimpin oleh Shigaraki dan All For One.",
  },
  {
    id: "9",
    title: "Re:Zero -Starting Life in Another World- Vol. 16",
    author: "Tappei Nagatsuki",
    publisher: "Elex Media Komputindo",
    publishYear: 2022,
    price: 95000,
    coverImage: "/starlit-promise.png",
    rating: 4.8,
    reviewCount: 130,
    stock: 15,
    isNew: false,
    isBestseller: true,
    categories: ["fiction", "light-novel"],
    language: "Indonesia",
    pageCount: 350,
    dimensions: "13 x 19 cm",
    isbn: "9786230040085",
    weight: 320,
    synopsis:
      "Subaru Natsuki tiba-tiba dipindahkan ke dunia fantasi dan mendapatkan kemampuan untuk 'Return by Death', memungkinkannya kembali ke titik tertentu setelah kematian. Volume 16 melanjutkan perjuangan Subaru di Arc 6 saat dia menghadapi tantangan di Menara Pleiades.",
  },
  {
    id: "10",
    title: "Attack on Titan Vol. 34",
    author: "Hajime Isayama",
    publisher: "Elex Media Komputindo",
    publishYear: 2021,
    price: 45000,
    originalPrice: 50000,
    coverImage: "/titan-siege.png",
    rating: 4.9,
    reviewCount: 250,
    stock: 10,
    isNew: false,
    isBestseller: true,
    categories: ["fiction", "manga"],
    language: "Indonesia",
    pageCount: 192,
    dimensions: "11.5 x 17.5 cm",
    isbn: "9786230032080",
    weight: 190,
    synopsis:
      "Volume final dari seri Attack on Titan yang legendaris. Eren Yeager telah memulai Rumbling untuk menghancurkan dunia di luar Paradis. Mikasa, Armin, dan teman-teman mereka harus menghentikannya untuk menyelamatkan umat manusia. Kesimpulan epik dari saga yang telah berlangsung selama lebih dari satu dekade.",
  },
]

export async function getBooks(options: any) {
  return { books: booksData, totalBooks: booksData.length, totalPages: 1 }
}

export async function getBookById(id: string) {
  return booksData.find((book) => book.id === id) || null
}

export async function getNewReleases() {
  return booksData.filter((book) => book.isNew)
}

export async function getBestsellers() {
  return booksData.filter((book) => book.isBestseller)
}

export async function getPromotions() {
  return booksData.filter((book) => book.originalPrice && book.originalPrice > book.price)
}

export async function getRelatedBooks(bookId: string, categories: string[]) {
  return booksData.filter(
    (book) => book.id !== bookId && book.categories?.some((category) => categories.includes(category)),
  )
}
